name: pokedex_manha
description: Pokédex criada para estudos.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dartz: ^0.9.2
  dio: ^4.0.0
  infinite_widgets: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: PokeGoTypes
      fonts:
        - asset: lib/assets/fonts/PokeGOTypes.ttf
    - family: PokemonSolid
      fonts:
        - asset: lib/assets/fonts/PokemonSolid.ttf